version: '3.8'

services:
  mongo: 
    image: mongo:4.2
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass123
      MONGO_INITDB_DATABASE: testDb
    ports:
      - 27017:27017
    volumes:
      - ./mongo_data:/data/db #mantener los datos guardados
